### ISSUE TITLE
Merge upstream security issue

### ISSUE THREAD

**Issue by eternal-flame-AD** [backrunner/misskey-media-proxy-worker#1]
Proxies can form infinite loops leading to amplification in certain circumstances. A partial fix has been submitted upstream:

https://github.com/misskey-dev/misskey/commit/48d1539f3be895b7aa8ecdd6c581e47a55cc9264

Is it possible for this be made RFC9110 compliant by sending a complaint Via header (which is a MUST-verbed item in RFC) and then some defensive programming against UAs of existing non compliant implementations that strip the Via header when proxying requests?

https://www.rfc-editor.org/rfc/rfc9110.html#section-7.6.3

> A proxy MUST send an appropriate Via header field, as described below, in each message that it forwards. An HTTP-to-HTTP gateway MUST send an appropriate Via header field in each inbound request message and MAY send a Via header field in forwarded response messages.

This is my implementation for reference: https://forge.yumechi.jp/yume/yumechi-no-kuni-proxy-worker/src/branch/main/src/fetch/mod.rs

**Comment by backrunner** [comment]
Sorry for the late response, I will investigate this issue soon and update the codes with a solution.
Thanks for your advice :D

**Comment by backrunner** [comment]
Already added via headers in proxy requests and response with loop proxy detection in `v0.4.0`, you can check it.

**Comment by eternal-flame-AD** [comment]
Thanks for fixing this! I glanced through https://github.com/backrunner/misskey-media-proxy-worker/commit/00b85b501efb1869b91d09e897c330111bbd5821 just two small comments:

(1) I think misskey user agent is capitalized like "Misskey/xxx" (I may be wrong the code may actually handle this correctly)
(2) It might not be too obvious why is there a config key for stripping via for specific UA's (to be honest I didn't understand either).

Overall I think as long as your proxy does not loop back to the same or another deployment of your own proxies (a.k.a require the cooperation of an external service to reshape the request) the risk is significantly reduced as Cloudflare is much more likely to detect this error for you.

I will also update my code to no longer reject connections to your default UA if the proper via is detected to reduce compatibility problems when some rare instance configuration can cause legitimate small-scale recursion.

**Comment by backrunner** [comment]
> Thanks for fixing this! I glanced through [00b85b5](https://github.com/backrunner/misskey-media-proxy-worker/commit/00b85b501efb1869b91d09e897c330111bbd5821) just two small comments:
> 
> (1) I think misskey user agent is capitalized like "Misskey/xxx" (I may be wrong the code may actually handle this correctly) (2) It might not be too obvious why is there a config key for stripping via for specific UA's (to be honest I didn't understand either).
> 
> Overall I think as long as your proxy does not loop back to the same or another deployment of your own proxies (a.k.a require the cooperation of an external service to reshape the request) the risk is significantly reduced as Cloudflare is much more likely to detect this error for you.
> 
> I will also update my code to no longer reject connections to your default UA if the proper via is detected to reduce compatibility problems when some rare instance configuration can cause legitimate small-scale recursion.

Here's my thought:
1) I'll patch my code with a `toLowerCase`.
2) To be honest, it's not necessary to provide an option to strip the header in the response, but make it configurable will make things more flexible if there's a weird client that cannot handle the `via` header in right way. The config option might be removed in the future, let's leave it at current.

====

I found there are something inconsistent in my code so I will change the default user agent value to "misskey/media-proxy-worker", also in the via header, I will push the changes in minutes, sorry for the inconvenience.
